vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       pictures:
           uri_prefix: /upload/pictures
           upload_destination: '%kernel.project_dir%/public/upload/pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
